dist: xenial
language: python
python:
  - "3.7"
jobs:
  include:
    - stage: test
    install:
      - pip install -r test-requirements.txt
      - pip install .
    script: pytest -s -vv --cov falcon_rpc --cov-report term-missing tests/