dist: xenial
language: python
cache: pip
jobs:
  include:
    - stage: test
      python: "3.7"
      before_install:
        - pip install --upgrade pip
      install:
        - pip install -r test-requirements.txt
        - pip install .
      script:
        - pytest -s -vv --cov falcon_rpc --cov-report=term-missing tests/